language: python

python:
  - "3.2"
  - "3.3"
  - "3.4"

env:
  - DJANGO_VERSION=1.7.2

install:
  - pip install .
  - pip install -r requirements.txt
  - pip install -q Django==$DJANGO_VERSION

script:
  - python example_project/manage.py test
