language: python

python:
  - "3.4"

env:
  - DJANGO_SETTINGS_MODULE=example_project.settings

install:
  - pip install . --use-mirrors
  - pip install -r requirements.txt --use-mirrors

script:
  - make test_basic
